esphome:
  name: piwnica
  friendly_name: piwnica

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "EI7Fwvf0FRocN0IbdQhNi5Tb75s/94eZ2gGjV+0NOGk="

ota:
  - platform: esphome
    password: "4870c8c776c2061a9888f6b206578580"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
    - ssid: !secret wifi_ssid_2
      password: !secret wifi_password_2
  use_address: "172.16.49.8"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Piwnica Fallback Hotspot"
    password: "W5LqpzrIVu1r"

i2c:
  sda: GPIO15
  scl: GPIO04
  scan: false
  id: bus_a

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

sun:
  latitude: 51.1634
  longitude: 17.0314

wireguard:
  address: 172.16.49.8
  private_key: !secret piwnica_private_key
  peer_endpoint: www.kena.pl
  peer_public_key: !secret piwnica_peer_public_key

  # Optional netmask (this is the default, no outgoing traffic
  # will pass through the tunnel if omitted)
  netmask: 255.255.255.255

  # Optional endpoint port (WireGuard default if omitted)
  peer_port: 51820

  # Optional pre-shared key (omit if not in use)
  peer_preshared_key: !secret piwnica_peer_preshared_key

  # Optional list of ip/mask (any host is allowed if omitted)
  #peer_allowed_ips:
  #  - x.y.z.0/24
  #  - l.m.n.o/32  # the /32 can be omitted for single host
  #  - [...]

  # Optional keepalive (disabled by default)
  peer_persistent_keepalive: 25s
  #require_connection_to_proceed: true

uart:
  id: ubus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

captive_portal:

# MOSFET Out
output:
  - platform: gpio
    inverted: True
    pin:
      number: GPIO18
    id: led_light

light:
  - platform: binary
    output: led_light
    name: piwnica_led
    id: piwn_led

ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware
sensor:
  - platform: ld2420
    moving_distance:
      name: "Moving Distance"
      id: moving_distance
      on_value_range:
        - below: 5.0
          then:
            - light.turn_off: piwn_led
        - above: 10.0
          then:
            - light.turn_on: piwn_led

  - platform: bmp280_i2c
    temperature:
      name: "Temperatura garaz"
      oversampling: 16x
    pressure:
      name: "Cisnienie pow"
    address: 0x76
    update_interval: 60s

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

select:
  - platform: ld2420
    operating_mode:
      name: "Operating Mode"

number:
  - platform: ld2420
    presence_timeout:
      name: "Detection Presence Timeout"
    min_gate_distance:
      name: "Detection Gate Minimum"
    max_gate_distance:
      name: "Detection Gate Maximum"
    gate_select:
      name: "Select Gate to Set"
    still_threshold:
      name: "Set Still Threshold Value"
    move_threshold:
      name: "Set Move Threshold Value"
    gate_move_sensitivity:
      name: "Move Calibration Sensitivity Factor"
    gate_still_sensitivity:
      name: "Still Calibration Sensitivity Factor"

button:
  - platform: ld2420
    apply_config:
      name: "Apply Config"
    factory_reset:
      name: "Factory Reset"
    restart_module:
      name: "Restart Module"
    revert_config:
      name: "Undo Edits"
